# Generated by Django 4.1.5 on 2023-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="owner",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
