# Generated by Django 4.1.5 on 2023-01-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_post_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="message",
            field=models.CharField(default="", max_length=128),
        ),
    ]
